### ISSUE TITLE
How to add the root_path and the trajectory_path.I got all the data,but I didn't know how to use it and I want konw how can I  use the data splits.I really need your help!

### ISSUE THREAD

**Issue by dengxw8** [VCL3D/DronePose#2]

**Comment by tzole1155** [comment]
Hi dengxw8,

I am going to close this issue as you have already opened another [one](https://github.com/VCL3D/UAVA/issues/1).

Best,

Giorgos

**Comment by dengxw8** [comment]
Dear sir
   Is it possible for me to get this code , The deadline of my graduation assignment is near and now I really need it to do the next step work.My graduation will be delayed if I can not finish this part ,It would be appreciated if you could help me with this.
   sincerely.

**Comment by tzole1155** [comment]
Hi dengxw8,

We are working on this.

In the meantime have a look at the following lines of [code](https://github.com/VCL3D/DronePose/blob/92be6b81b5756c1e59f2254288f05ed53f7ee98d/train.py#L191) where we the test function has been defined.

Best,

Giorgos

**Comment by tzole1155** [comment]
Hi dengxw8,

We have added the [inference](https://github.com/VCL3D/DronePose/blob/master/infer.py) code.

I have it tested it locally  and it worked as expected.

Best,

Giorgos

**Comment by dengxw8** [comment]
Thanks for all your help!
