### ISSUE TITLE
Can I have the link of the YouTube video of the drone 

### ISSUE THREAD

**Issue by DoranLyong** [VCL3D/DronePose#3]
Hi, I'm very interested in your study and have tried to run the ```infer.py``` with your pretrained model.  <br/>
I googled one image of the DJI enterprise model of the drone for the test and gave it as an input, but the output seemed bad.<br/> I tried a few other sample images which looked like the DJI drone in ```./data/DJI.obj ``` and the outputs were still bad. <br/> 

So, I wonder about the resource link of the drone video involved in  ```./data/Outdoor_1.gif ```.

**Comment by tzole1155** [comment]
Hi DoranLyong,
Thanks for your interest in our work.
Please find attached the extracted frames from the YouTube video, used for creating the gif file.
[gif_1.zip](https://github.com/VCL3D/DronePose/files/6601058/gif_1.zip)
Best,
Giorgos

**Comment by DoranLyong** [comment]
Thanks for your fast response! @tzole1155  <br/>

I tested with your pretrained ```Gauss0.1``` model noticed in your ECCVW2020 paper. <br/>
However, I got still the wrong outputs... </br>

I input the options as the arguments like:
``` pyhton 
    parser.add_argument("--input_path", type = str, default='./gif_1' , help = "Path to the root folder containing all the images")
    parser.add_argument("--output_path", type = str, default='./output_results' ,help = "Path for saving the blended images")                  
    # model
    parser.add_argument('--model', type=str, default="resnet34", help='Model name')
    parser.add_argument('--head', type=str, default="continuous", help='Head name')
    parser.add_argument('--weights', type=str, default="./pretrained_model/Gauss0.1", help='Path to the trained weights file.')    
    parser.add_argument("--exocentric_w", type=float, default=0.1, help = " Exocentric silhouette supervision loss regulariser.")
    parser.add_argument('--colour',type=str,default='red',help = "Colour to be used for the final blended image")
```

and I had like this: 
![frame3267](https://user-images.githubusercontent.com/13333380/120882139-ac742000-c610-11eb-915a-50da1dab307a.png)

Could you advise me to solve this issue?

**Comment by tzole1155** [comment]
Hi Lyong,

Could you provide some details about your environment (e.g. PyTorch version, Kaolin, OS, etc.)

Could you also verify that you have downloaded the weights and properly set them?

Also, do you use a GPU for running the code?

Apart from these, it would be useful to provide a screenshot from the terminal.

Giorgos

**Comment by DoranLyong** [comment]
Good morning @tzole1155 

Let me describe my environment setttings: 
* Ubuntu 20.04
* Titan XP GPU
* the package versions are: 
![image](https://user-images.githubusercontent.com/13333380/120983252-7e2f4580-c7b4-11eb-8bda-30fbc8fcf669.png)

<br/>

I did download the weights from below links and chose ```Gauss0.1 @ epoch 20``` version:
![image](https://user-images.githubusercontent.com/13333380/120983437-a8810300-c7b4-11eb-9a1b-c134d168ab96.png)

<br/>

and saved it in a directory; ```pretrained_model``` like: 
![image](https://user-images.githubusercontent.com/13333380/120984633-d0bd3180-c7b5-11eb-8044-bc578b62eeaf.png)

<br/>

Finally, I ran the inference code giving the arguments like this:
![image](https://user-images.githubusercontent.com/13333380/120985724-db2bfb00-c7b6-11eb-872d-436e9b300f37.png)



It seems that there is some input size issue?! <br/>

**Comment by tzole1155** [comment]
Hi @DoranLyong,

Yes, something does not seem entirely correct.

Could you print the predicted poses per image and send them to me in order to verify that we get the same network predictions?
You could add a print statement after https://github.com/VCL3D/DronePose/blob/master/infer.py#L71.

Best,

Giorgos

**Comment by DoranLyong** [comment]
Thanks for your appreciation. <br/>

I involved the prediction values in a ```.pt``` file and a test loading code: 
* you can download the prediction values from [this link](https://drive.google.com/file/d/1CUUfyMmzPH1xSMoNFNnvUmZS4s1_yhOo/view?usp=sharing). 
*  the sample code for loading the data is :
```python 
import torch 

pred = torch.load('prediction_test.pt')


#print(pred.keys())


for key, values in pred.items():
    print("image name", key)
    pred_rot_matrix = values[0]
    pred_translation = values[1]
    
    print("rot: ", pred_rot_matrix)
    print("trans: ", pred_translation) 

``` 

I used the youtube video frames which you gave me before. 


<br/>

I made them by simply editing some parts like in https://github.com/VCL3D/DronePose/blob/master/infer.py#L71: 
![image](https://user-images.githubusercontent.com/13333380/120997906-8db58b00-c7c2-11eb-98e0-6cd96f0a4c8c.png)

**Comment by DoranLyong** [comment]
Okay, I discovered some reproducibility issues. <br/> 

I had tested your inference code under my docker container. 
Those issues above are the inference results out of the docker container with conda.<br/>
![frame3267](https://user-images.githubusercontent.com/13333380/121019767-b21d6180-c7da-11eb-9893-b50e825bc9b5.png)

<br/> 

After then, I tested under my local HOST with conda with the same environment settings. <br/>
I got the true results. 
![frame3267](https://user-images.githubusercontent.com/13333380/121019806-ba759c80-c7da-11eb-855b-fa00140d1836.png)

<br/>

I set both in the same conditions following the requirement instructions <br/>
* the same torch version 
* the same kaolin version 
![image](https://user-images.githubusercontent.com/13333380/121020207-1d673380-c7db-11eb-93a1-1700246806c7.png)

(left) out of the local host ,  (right) out of the docker container 

<br/> 

Even though I'm really really running the same [infer.py](https://github.com/VCL3D/DronePose/blob/master/infer.py#L71) code with the same model weights, 
I have no idea why the inference model returned difference values according to both local HOST and docker container :s.

<br/>

![image](https://user-images.githubusercontent.com/13333380/121021385-4b00ac80-c7dc-11eb-9d6d-a328ebc071b8.png)

<br/>

※ I did mount the local workspace to the docker container, so the code conditions are the same.

**Comment by DoranLyong** [comment]
okay ... I think I discovered the reason. <br/> 

Even though I set the reproducibility set up [following](https://pytorch.org/docs/stable/notes/randomness.html):
```python
torch.manual_seed(42)
torch.cuda.manual_seed(42)
torch.cuda.manual_seed_all(42) 

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
``` 

the results of the docker are different and wrong.


When I checked them in detail, I caught out both `cuda version`s were sort of different : 
* `torch==1.8.1+cu102` (local HOST)  ; true case 
* `torch==1.8.1+cu111` (docker container) ; false case 

I didn't suspect the cuda version may affect the results, but I just reinstalled the torch package from `torch==1.8.1+cu111` to `torch==1.8.1+cu102`. In ridiculous, I got the correct outputs :s ...... <br/>

local HOST: 
![frame3396](https://user-images.githubusercontent.com/13333380/121028313-afbf0580-c7e2-11eb-81aa-4d58fe32649c.png)

docker container:
![frame3396](https://user-images.githubusercontent.com/13333380/121028334-b483b980-c7e2-11eb-9f2b-13c3ffaec08c.png)


I reinstalled: 
* `torch==1.8.1+cu102`
* `torchvision==0.9.1+cu102`


I couldn't anticipate that `cuda version` can make pretty much different results.

**Comment by DoranLyong** [comment]
Yes, the [official repository](https://github.com/NVIDIAGameWorks/kaolin/tree/v0.1) also said it is okay to install `CUDA >= 10.0.130` :s <br/>  

![image](https://user-images.githubusercontent.com/13333380/121030667-a6369d00-c7e4-11eb-9508-b5cf4423cb57.png)


Why does the model with `torch==1.8.1+cu111` version return bad results? ...

**Comment by tzole1155** [comment]
Hi @DoranLyong,
Thanks for spending time figuring this out.
As mentioned in the README we have tested our code with Python 3.6 and CUDA 10.1.
Best,
Giorgos
